name: build
on:
  push:
    branches:
      - main
  pull_request:
env:
  TRIVY_VERSION: 0.51.1
  WORKING_DIRECTORY: terraform/mask
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@b2933f565dbc598b29947660e66259e3c7bc8561
        with:
          scan-type: 'config'
          hide-progress: true
          trivyignores: ${{ env.WORKING_DIRECTORY }}/.trivyignore
